#!/bin/bash

#export TAU_METRICS "TIME,PAPI_NATIVE_PM_LD_L3MISS_PEND_CYC,PAPI_NATIVE_PM_RUN_CYC,PAPI_NATIVE_PM_RUN_INST_CMPL,PAPI_NATIVE_PM_DATA_FROM_L3MISS,PAPI_NATIVE_PM_INST_FROM_L3MISS"

#export TAU_PLUGINS libTAU-adios2-trace-plugin.so
#export TAU_PLUGINS_PATH /lustre/ssinghal/tau2-install1/x86_64/lib/shared-papi-mpi-pthread-adios2
#export TAU_ADIOS2_PERIODIC 1
#export TAU_ADIOS2_PERIOD 5000000
#export TAU_ADIOS2_ONE_FILE 0
#export TAU_ADIOS2_ENGINE SST
#export TAU_ADIOS2_FILENAME 'tau-adios2-metrics'

#export TAU_THROTTLE_NUMCALLS 50
#export TAU_THROTTLE_PERCALL 500
#export TAU_TRACK_MEMORY_FOOTPRINT 1
#export TAU_PAPI_MULTIPLEXING 1
#export TAU_PROFILE 0
#export TAU_TRACE 1
#export SstVerbose 1
export OMP_NUM_THREADS=1

export SAVANNA_WORKFLOW_FILE="workflow_dag.txt"
export SAVANNA_MONITOR_MODEL="outsteps2"
export SAVANNA_RESTART_PIPELINE=1
export SAVANNA_RESTART_STEPS=200 


